name: Deploy to GitHub Pages

on:
  # 每次推送到 main 分支时触发部署
  push:
    branches: ["main"]
  # 允许手动触发部署
  workflow_dispatch:

# 设置 GITHUB_TOKEN 的权限，以允许部署到 GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# 允许一个并发的部署
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          
      - name: Check Node and npm versions
        run: node --version && npm --version
        
      - name: Clear npm cache
        run: npm cache clean --force
        
      - name: Install dependencies
        run: npm ci --legacy-peer-deps
        
      - name: Build
        run: npm run build
        env:
          VITE_GEMINI_API_KEY: 1753011b170839263d22262f11744061500e33193922190a3259502f33337c697f63410b103b226f3d2d0d3c3d09665c660158463343031c06435d3a3f3b1c0f66665e7f
          VITE_GEMINI_API_ENDPOINT: https://api-666.cc/v1/chat/completions
        
      - name: Setup Pages
        uses: actions/configure-pages@v4
        
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          # 上传 dist 文件夹
          path: './dist'
          
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
